<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class RawMaterialsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('raw_materials')->delete();
        
        \DB::table('raw_materials')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Steel Sheet A36',
                'slug' => 'steel-sheet-a36',
                'code' => 'STL-A36-001',
                'barcode' => NULL,
                'raw_material_category_id' => 1,
                'purchase_unit_id' => 1,
                'purchase_price' => 2.5,
                'consumption_unit_id' => 1,
                'conversion_rate' => 1.0,
                'consumption_price' => 2.5,
                'stock' => 1500.0,
                'alert_stock' => 100.0,
                'image' => NULL,
                'description' => 'High-quality carbon steel sheet for construction and manufacturing',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Aluminum Alloy 6061',
                'slug' => 'aluminum-alloy-6061',
                'code' => 'ALU-6061-002',
                'barcode' => NULL,
                'raw_material_category_id' => 1,
                'purchase_unit_id' => 1,
                'purchase_price' => 4.75,
                'consumption_unit_id' => 1,
                'conversion_rate' => 1.0,
                'consumption_price' => 4.75,
                'stock' => 800.0,
                'alert_stock' => 50.0,
                'image' => NULL,
                'description' => 'Versatile aluminum alloy with excellent corrosion resistance',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Polypropylene Resin',
                'slug' => 'polypropylene-resin',
                'code' => 'PP-RES-003',
                'barcode' => NULL,
                'raw_material_category_id' => 2,
                'purchase_unit_id' => 1,
                'purchase_price' => 1.85,
                'consumption_unit_id' => 2,
                'conversion_rate' => 1000.0,
                'consumption_price' => 0.00185,
                'stock' => 2500.0,
                'alert_stock' => 200.0,
                'image' => NULL,
                'description' => 'Thermoplastic polymer for injection molding applications',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Industrial Acetone',
                'slug' => 'industrial-acetone',
                'code' => 'ACT-IND-004',
                'barcode' => NULL,
                'raw_material_category_id' => 3,
                'purchase_unit_id' => 3,
                'purchase_price' => 3.2,
                'consumption_unit_id' => 4,
                'conversion_rate' => 1000.0,
                'consumption_price' => 0.0032,
                'stock' => 500.0,
                'alert_stock' => 25.0,
                'image' => NULL,
                'description' => 'High-purity solvent for cleaning and degreasing',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Cotton Canvas 12oz',
                'slug' => 'cotton-canvas-12oz',
                'code' => 'CTN-CNV-005',
                'barcode' => NULL,
                'raw_material_category_id' => 4,
                'purchase_unit_id' => 6,
                'purchase_price' => 8.5,
                'consumption_unit_id' => 7,
                'conversion_rate' => 100.0,
                'consumption_price' => 0.085,
                'stock' => 300.0,
                'alert_stock' => 20.0,
                'image' => NULL,
                'description' => 'Heavy-duty cotton canvas for industrial applications',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Pine Plywood 18mm',
                'slug' => 'pine-plywood-18mm',
                'code' => 'PLY-PIN-006',
                'barcode' => NULL,
                'raw_material_category_id' => 5,
                'purchase_unit_id' => 8,
                'purchase_price' => 45.0,
                'consumption_unit_id' => 8,
                'conversion_rate' => 1.0,
                'consumption_price' => 45.0,
                'stock' => 150.0,
                'alert_stock' => 10.0,
                'image' => NULL,
                'description' => 'High-grade pine plywood for furniture and construction',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Tempered Glass 6mm',
                'slug' => 'tempered-glass-6mm',
                'code' => 'GLS-TMP-007',
                'barcode' => NULL,
                'raw_material_category_id' => 6,
                'purchase_unit_id' => 8,
                'purchase_price' => 75.0,
                'consumption_unit_id' => 8,
                'conversion_rate' => 1.0,
                'consumption_price' => 75.0,
                'stock' => 80.0,
                'alert_stock' => 5.0,
                'image' => NULL,
                'description' => 'Safety glass for windows and architectural applications',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Natural Rubber Latex',
                'slug' => 'natural-rubber-latex',
                'code' => 'RUB-LAT-008',
                'barcode' => NULL,
                'raw_material_category_id' => 7,
                'purchase_unit_id' => 1,
                'purchase_price' => 3.8,
                'consumption_unit_id' => 2,
                'conversion_rate' => 1000.0,
                'consumption_price' => 0.0038,
                'stock' => 600.0,
                'alert_stock' => 30.0,
                'image' => NULL,
                'description' => 'Premium natural rubber for manufacturing applications',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Copper Wire 14AWG',
                'slug' => 'copper-wire-14awg',
                'code' => 'COP-WIR-009',
                'barcode' => NULL,
                'raw_material_category_id' => 8,
                'purchase_unit_id' => 6,
                'purchase_price' => 2.15,
                'consumption_unit_id' => 7,
                'conversion_rate' => 100.0,
                'consumption_price' => 0.0215,
                'stock' => 2000.0,
                'alert_stock' => 100.0,
                'image' => NULL,
                'description' => 'High-conductivity copper wire for electrical applications',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Portland Cement Type I',
                'slug' => 'portland-cement-type-i',
                'code' => 'CEM-POR-010',
                'barcode' => NULL,
                'raw_material_category_id' => 10,
                'purchase_unit_id' => 1,
                'purchase_price' => 0.12,
                'consumption_unit_id' => 1,
                'conversion_rate' => 1.0,
                'consumption_price' => 0.12,
                'stock' => 10000.0,
                'alert_stock' => 500.0,
                'image' => NULL,
                'description' => 'Standard portland cement for general construction use',
                'status' => 'Active',
                'created_by' => 1,
                'deleted_at' => NULL,
                'created_at' => '2025-06-29 09:32:31',
                'updated_at' => '2025-06-29 09:32:31',
            ),
        ));
        
        
    }
}